/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package variaveisOperadores;

public class App {
    
    public static void main(String[] args) {
        int idade;
        float cotacaoDolar = 5.0f;
        double cotacaoEuro = 6.35d;
        char genero = 'M';
        String nome = "Nesse usa aspas duplas";
    }
}
